//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySuperPuperProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиенты
    {
        public string ФИО { get; set; }
        public string Код_клиента { get; set; }
        public string Серия_паспорта { get; set; }
        public string Номер_паспорта { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Индекс { get; set; }
        public string Город { get; set; }
        public string Улица { get; set; }
        public string Дом { get; set; }
        public string Квартира { get; set; }
        public string e_mail { get; set; }
        public string password { get; set; }
    }
}
